per_page:
  default: 10
  course_index: 12
user:
  name:
    minlength: 3
    maxlength: 70
  email:
    maxlength: 70
  password:
    minlength: 6
    maxlength: 30
master_subject:
  creadit:
    greater: 1
    less: 20
  name:
    maxlength: 70
  code:
    maxlength: 10
master_class:
  name:
    maxlength: 70
  code:
    maxlength: 10
master_course:
  name:
    maxlength: 10
  code:
    maxlength: 10
room:
  name:
    minlength: 3
    maxlength: 10
  code:
    minlength: 3
    maxlength: 10
